#!/usr/bin/env bash

working_dir="$HOME/.ddnss-update"
log_file="$HOME/.ddnss-update/ddnss-update.log"
current_date=`date +%Y-%m-%d\ %H:%M:%S`

if [ ! -f $working_dir/last.ip4 ]; then
    mkdir -p $working_dir
    touch $working_dir/last.ip4
fi

if [ ! -f $working_dir/last.ip6 ]; then
    mkdir -p $working_dir
    touch $working_dir/last.ip6
fi

if [ ! -f $working_dir/keyauth ]; then
    mkdir -p $working_dir
    touch $working_dir/keyauth
fi

if [ ! -f $working_dir/hostname ]; then
    mkdir -p $working_dir
    touch $working_dir/hostname
fi

function help {
    echo "USAGE: $0 <UPDATE-KEY> <HOST>"
}

function logmsg {
    echo "$current_date - $@" >> $log_file
}

if [ "$#" -eq 2 ]; then
    keyauth=$1
    hostname=$2
elif [ "$#" -eq 0 ]; then
    keyauth=$(cat $working_dir/keyauth)
    hostname=$(cat $working_dir/hostname)
else
    echo "Illegal number of parameters"
    help
    exit 1
fi

ip6=`curl http://www.ddnss.de/meineip.php 2>/dev/null| grep -o '[0-9a-z]\{1,4\}\:[0-9a-z]\{1,4\}\:[0-9a-z]\{1,4\}\:[0-9a-z]\{1,4\}\:[0-9a-z]\{1,4\}\:[0-9a-z]\{1,4\}\:[0-9a-z]\{1,4\}\:[0-9a-z]\{1,4\}'`
ip4=`curl http://217.79.184.12/meineip.php 2>/dev/null| grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`

updip4=`cat $working_dir/last.ip4 2>/dev/null || echo -en ''`
updip6=`cat $working_dir/last.ip6 2>/dev/null || echo -en ''`

logmsg "Current IP=$updip4"
logmsg "Current IP=$updip6"

if [ "$ip4" == "$updip4" -a "$ip6" == "$updip6" ]; then
    logmsg "IP is the same - NO UPDATE"
    echo "No update"
else
    logmsg "New IP4: $ip4 / Old ip4: $updip - UPDATE"
    logmsg "New IP6: $ip6 / Old ip6: $updip6 - UPDATE"

   echo $ip4 > $working_dir/last.ip4
   echo $ip6 > $working_dir/last.ip6

   wget -q -O - 'https://www.ddnss.de/upd.php?key='$keyauth'&host='$hostname'&ip='$ip4'&ip6='$ip6 >> $log_file

   echo "Update ($ip4)"
   echo "Update ($ip6)"
fi
